"""added customer phone rltshp

Revision ID: 899601259427
Revises: ed9280940c8d
Create Date: 2023-06-06 21:52:52.097150

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '899601259427'
down_revision = 'ed9280940c8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
